[tool.poetry]
name = "tea"
version = "0.0.1"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
clidantic = "^0.1.0"
pydantic = "1.10.14"
numpy = "^1.26.3"
hexbytes = "^0.2.3"
pyevmasm = "^0.2.3"
torch = "^2.2.0"
torchvision = "^0.17.0"
datasets = "^2.16.1"
scikit-learn = "^1.4.0"
slither = "^0.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
